"""GPS data model

Revision ID: 06746a9e7bbe
Revises: 19d461649c71
Create Date: 2025-10-30 16:54:46.520766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06746a9e7bbe"
down_revision: Union[str, Sequence[str], None] = "19d461649c71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gps_tracking",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vehicle_no", sa.String(), nullable=False),
        sa.Column("imei", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("speed", sa.Float(), nullable=False),
        sa.Column("ignition", sa.Boolean(), nullable=False),
        sa.Column("total_gps_odometer", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_timestamp", "gps_tracking", ["timestamp"], unique=False)
    op.create_index("idx_vehicle", "gps_tracking", ["vehicle_no"], unique=False)
    op.create_index("idx_vehicle_timestamp", "gps_tracking", ["vehicle_no", "timestamp"], unique=False)
    op.create_index(op.f("ix_gps_tracking_timestamp"), "gps_tracking", ["timestamp"], unique=False)
    op.create_index(op.f("ix_gps_tracking_vehicle_no"), "gps_tracking", ["vehicle_no"], unique=False)
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=False)
    op.drop_index(op.f("ix_gps_tracking_vehicle_no"), table_name="gps_tracking")
    op.drop_index(op.f("ix_gps_tracking_timestamp"), table_name="gps_tracking")
    op.drop_index("idx_vehicle_timestamp", table_name="gps_tracking")
    op.drop_index("idx_vehicle", table_name="gps_tracking")
    op.drop_index("idx_timestamp", table_name="gps_tracking")
    op.drop_table("gps_tracking")
    # ### end Alembic commands ###
