"""Agency, Contractor and Attendance models

Revision ID: 08729624e5bc
Revises: 76865e89aa5d
Create Date: 2025-09-27 17:49:09.470744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08729624e5bc'
down_revision: Union[str, Sequence[str], None] = '76865e89aa5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('phone', sa.VARCHAR(), nullable=True),
        sa.Column('email', sa.VARCHAR(), nullable=True),
        sa.Column('address', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('contractors',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('agency_id', sa.INTEGER(), nullable=False),
        sa.Column('person_name', sa.VARCHAR(), nullable=True),
        sa.Column('person_phone', sa.VARCHAR(), nullable=True),
        sa.Column('village_id', sa.INTEGER(), nullable=True),
        sa.Column('contract_start_date', sa.TIMESTAMP(), nullable=True),
        sa.Column('contract_end_date', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
        sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('contractor_id', sa.INTEGER(), nullable=False),
        sa.Column('date', sa.DATE(), nullable=False),
        sa.Column('status', sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('contractor_id', 'date', name='uq_contractor_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('contractors')
    op.drop_table('agencies')