"""refactor_survey_assets_categories

Revision ID: 1408ebb1fea3
Revises: d0dfbe7ab554
Create Date: 2026-03-30 00:35:50.431587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1408ebb1fea3'
down_revision: Union[str, Sequence[str], None] = 'd0dfbe7ab554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_d2d_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sanctioned_tender', sa.Integer(), nullable=False),
    sa.Column('sanctioned_self_gp', sa.Integer(), nullable=False),
    sa.Column('sanctioned_csr_ngo', sa.Integer(), nullable=False),
    sa.Column('sanctioned_shg', sa.Integer(), nullable=False),
    sa.Column('total_expenditure', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vehicles_deployed', sa.Integer(), nullable=False),
    sa.Column('persons_deployed', sa.Integer(), nullable=False),
    sa.Column('households_covered', sa.Integer(), nullable=False),
    sa.Column('status_start', sa.Integer(), nullable=False),
    sa.Column('status_running', sa.Integer(), nullable=False),
    sa.Column('status_completed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_fsm_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twin_pit_toilets', sa.Integer(), nullable=False),
    sa.Column('single_pit_toilets', sa.Integer(), nullable=False),
    sa.Column('septic_tank_toilets', sa.Integer(), nullable=False),
    sa.Column('retrofitted_toilets', sa.Integer(), nullable=False),
    sa.Column('mechanized_desludging', sa.Integer(), nullable=False),
    sa.Column('fstps_rural', sa.Integer(), nullable=False),
    sa.Column('fstps_urban', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_gobardhan_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_projects', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_lwm_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pits_hh_level', sa.Integer(), nullable=False),
    sa.Column('community_pits', sa.Integer(), nullable=False),
    sa.Column('wsp', sa.Integer(), nullable=False),
    sa.Column('dewats', sa.Integer(), nullable=False),
    sa.Column('wetlands', sa.Integer(), nullable=False),
    sa.Column('other_treatments', sa.Integer(), nullable=False),
    sa.Column('drainage_channels', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_odf_sustainability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ihhl', sa.Integer(), nullable=False),
    sa.Column('retrofitting', sa.Integer(), nullable=False),
    sa.Column('csc', sa.Integer(), nullable=False),
    sa.Column('csc_shala_darpan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_pwmu_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('established_pwmu', sa.Integer(), nullable=False),
    sa.Column('blocks_covered_pwmu', sa.Integer(), nullable=False),
    sa.Column('urban_mrfs', sa.Integer(), nullable=False),
    sa.Column('blocks_covered_urban_mrf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_swm_assets_new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bins_hh_level', sa.Integer(), nullable=False),
    sa.Column('bins_public_places', sa.Integer(), nullable=False),
    sa.Column('community_compost_pits', sa.Integer(), nullable=False),
    sa.Column('segregation_sheds', sa.Integer(), nullable=False),
    sa.Column('tricycles_manual', sa.Integer(), nullable=False),
    sa.Column('e_rickshaws', sa.Integer(), nullable=False),
    sa.Column('motorized_vehicles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('survey_swm_assets')
    op.drop_index(op.f('ix_annual_survey_financial_year_fy'), table_name='annual_survey_financial_year')
    op.create_index(op.f('ix_annual_survey_financial_year_fy'), 'annual_survey_financial_year', ['fy'], unique=True)
    op.drop_column('complaint_media', 'user_id')
    op.drop_column('complaint_media', 'user_type')
    op.drop_column('event_media', 'user_id')
    op.drop_column('event_media', 'user_type')
    op.drop_column('inspection_images', 'user_id')
    op.drop_column('inspection_images', 'user_type')
    op.drop_column('notice_media', 'user_id')
    op.drop_column('notice_media', 'user_type')
    op.drop_column('scheme_media', 'user_id')
    op.drop_column('scheme_media', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheme_media', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scheme_media', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notice_media', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notice_media', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inspection_images', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('inspection_images', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event_media', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_media', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('complaint_media', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('complaint_media', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_annual_survey_financial_year_fy'), table_name='annual_survey_financial_year')
    op.create_index(op.f('ix_annual_survey_financial_year_fy'), 'annual_survey_financial_year', ['fy'], unique=False)
    op.create_table('survey_swm_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rrc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pwmu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('compost_pit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_vehicle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], name=op.f('survey_swm_assets_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('survey_swm_assets_pkey'))
    )
    op.drop_table('survey_swm_assets_new')
    op.drop_table('survey_pwmu_details')
    op.drop_table('survey_odf_sustainability')
    op.drop_table('survey_lwm_assets')
    op.drop_table('survey_gobardhan_projects')
    op.drop_table('survey_fsm_details')
    op.drop_table('survey_d2d_activities')
    # ### end Alembic commands ###
