"""Add annual survey models and relationships

Revision ID: 14571a14cd51
Revises: 5145124937a3
Create Date: 2025-10-12 19:46:40.072598

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14571a14cd51"
down_revision: Union[str, Sequence[str], None] = "5145124937a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annual_surveys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gp_id", sa.Integer(), nullable=False),
        sa.Column("survey_date", sa.Date(), nullable=False),
        sa.Column("vdo_id", sa.Integer(), nullable=False),
        sa.Column("sarpanch_name", sa.String(length=255), nullable=True),
        sa.Column("sarpanch_contact", sa.String(length=20), nullable=True),
        sa.Column("num_ward_panchs", sa.Integer(), nullable=True),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gp_id"],
            ["villages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vdo_id"],
            ["authority_holder_persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annual_surveys_gp_id"), "annual_surveys", ["gp_id"], unique=False
    )
    op.create_index(
        "ix_annual_surveys_gp_id_survey_date",
        "annual_surveys",
        ["gp_id", "survey_date"],
        unique=False,
    )
    op.create_index(
        "ix_annual_surveys_survey_date", "annual_surveys", ["survey_date"], unique=False
    )
    op.create_table(
        "survey_csc_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numbers", sa.Integer(), nullable=True),
        sa.Column(
            "cleaning_frequency",
            sa.Enum(
                "DAILY",
                "ALTERNATE_DAYS",
                "TWICE_A_WEEK",
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "NONE",
                name="csc_cleaning_frequency",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_door_to_door_collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("num_households", sa.Integer(), nullable=True),
        sa.Column("num_shops", sa.Integer(), nullable=True),
        sa.Column(
            "collection_frequency",
            sa.Enum(
                "DAILY",
                "ALTERNATE_DAYS",
                "TWICE_A_WEEK",
                "WEEKLY",
                "FORTNIGHTLY",
                "NONE",
                name="collection_frequency",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_drain_cleaning",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("length", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "cleaning_frequency",
            sa.Enum(
                "DAILY",
                "ALTERNATE_DAYS",
                "TWICE_A_WEEK",
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "NONE",
                name="drain_cleaning_frequency",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_fund_sanctioned",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "head",
            sa.Enum("FFC", "SFC", "CSR", "OWN_INCOME", "OTHER", name="fund_head"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_road_sweeping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("width", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("length", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "cleaning_frequency",
            sa.Enum(
                "DAILY",
                "ALTERNATE_DAYS",
                "TWICE_A_WEEK",
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "NONE",
                name="road_cleaning_frequency",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_sbmg_year_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ihhl", sa.Integer(), nullable=True),
        sa.Column("csc", sa.Integer(), nullable=True),
        sa.Column("rrc", sa.Integer(), nullable=True),
        sa.Column("pwmu", sa.Integer(), nullable=True),
        sa.Column("soak_pit", sa.Integer(), nullable=True),
        sa.Column("magic_pit", sa.Integer(), nullable=True),
        sa.Column("leach_pit", sa.Integer(), nullable=True),
        sa.Column("wsp", sa.Integer(), nullable=True),
        sa.Column("dewats", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_swm_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rrc", sa.Integer(), nullable=True),
        sa.Column("pwmu", sa.Integer(), nullable=True),
        sa.Column("compost_pit", sa.Integer(), nullable=True),
        sa.Column("collection_vehicle", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_village_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("village_name", sa.String(length=255), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("num_households", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["survey_id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_survey_village_data_survey_id"),
        "survey_village_data",
        ["survey_id"],
        unique=False,
    )
    op.create_table(
        "survey_work_order_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_order_no", sa.String(length=100), nullable=True),
        sa.Column("work_order_date", sa.Date(), nullable=True),
        sa.Column(
            "work_order_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_village_gwm_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("soak_pit", sa.Integer(), nullable=True),
        sa.Column("magic_pit", sa.Integer(), nullable=True),
        sa.Column("leach_pit", sa.Integer(), nullable=True),
        sa.Column("wsp", sa.Integer(), nullable=True),
        sa.Column("dewats", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["survey_village_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_village_sbmg_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ihhl", sa.Integer(), nullable=True),
        sa.Column("csc", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["survey_village_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("survey_village_sbmg_assets")
    op.drop_table("survey_village_gwm_assets")
    op.drop_table("survey_work_order_details")
    op.drop_index(
        op.f("ix_survey_village_data_survey_id"), table_name="survey_village_data"
    )
    op.drop_table("survey_village_data")
    op.drop_table("survey_swm_assets")
    op.drop_table("survey_sbmg_year_targets")
    op.drop_table("survey_road_sweeping")
    op.drop_table("survey_fund_sanctioned")
    op.drop_table("survey_drain_cleaning")
    op.drop_table("survey_door_to_door_collection")
    op.drop_table("survey_csc_details")
    op.drop_index("ix_annual_surveys_survey_date", table_name="annual_surveys")
    op.drop_index("ix_annual_surveys_gp_id_survey_date", table_name="annual_surveys")
    op.drop_index(op.f("ix_annual_surveys_gp_id"), table_name="annual_surveys")
    op.drop_table("annual_surveys")
    # ### end Alembic commands ###
