"""add is_active to circulars

Revision ID: 1491c038bf73
Revises: e2e40fab6e3c
Create Date: 2026-07-12 12:06:24.123817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1491c038bf73'
down_revision: Union[str, Sequence[str], None] = 'e2e40fab6e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annual_survey_financial_year_fy'), table_name='annual_survey_financial_year')
    op.create_index('ix_annual_survey_financial_year_fy', 'annual_survey_financial_year', ['fy'], unique=False)
    op.add_column('circulars', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('circulars', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circulars', 'is_active')
    op.drop_index('ix_annual_survey_financial_year_fy', table_name='annual_survey_financial_year')
    op.create_index(op.f('ix_annual_survey_financial_year_fy'), 'annual_survey_financial_year', ['fy'], unique=True)
    # ### end Alembic commands ###
