"""Add village name field to inspection

Revision ID: 19d461649c71
Revises: a9b3c4d5e6f7
Create Date: 2025-10-26 12:30:30.170027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19d461649c71"
down_revision: Union[str, Sequence[str], None] = "a9b3c4d5e6f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("middle_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("mobile_number", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_employees_employee_id"), "employees", ["employee_id"], unique=True)
    op.create_index(op.f("ix_employees_first_name"), "employees", ["first_name"], unique=False)
    op.create_index(op.f("ix_employees_mobile_number"), "employees", ["mobile_number"], unique=True)
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index("ix_annual_survey_financial_year_fy", "annual_survey_financial_year", ["fy"], unique=False)
    op.add_column("inspections", sa.Column("village_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inspections", "village_name")
    op.drop_index("ix_annual_survey_financial_year_fy", table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    op.drop_index(op.f("ix_employees_mobile_number"), table_name="employees")
    op.drop_index(op.f("ix_employees_first_name"), table_name="employees")
    op.drop_index(op.f("ix_employees_employee_id"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
