"""use stringified location for frontend screens

Revision ID: 1b00c884998c
Revises: 8552eca07acc
Create Date: 2025-10-24 17:07:35.791929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b00c884998c'
down_revision: Union[str, Sequence[str], None] = '8552eca07acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annual_survey_financial_year_fy'), table_name='annual_survey_financial_year')
    op.create_index('ix_annual_survey_financial_year_fy', 'annual_survey_financial_year', ['fy'], unique=False)
    op.add_column('complaints', sa.Column('location', sa.String(), server_default='location', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'location')
    op.drop_index('ix_annual_survey_financial_year_fy', table_name='annual_survey_financial_year')
    op.create_index(op.f('ix_annual_survey_financial_year_fy'), 'annual_survey_financial_year', ['fy'], unique=True)
    # ### end Alembic commands ###
