"""GP ID indexes

Revision ID: 1f40e69ca42e
Revises: ca70cf2fd644
Create Date: 2025-10-11 14:21:31.797145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f40e69ca42e"
down_revision: Union[str, Sequence[str], None] = "ca70cf2fd644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inspection_household_waste_collection_and_disposal_inspection_i")
    op.execute("DROP TYPE IF EXISTS waste_coll_freq")
    op.create_table(
        "inspection_household_waste_collection_and_disposal_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "waste_collection_frequency",
            sa.Enum(
                "DAILY",
                "ONCE_IN_THREE_DAYS",
                "WEEKLY",
                "NONE",
                name="waste_coll_freq",
            ),
            nullable=True,
        ),
        sa.Column("dry_wet_vehicle_segregation", sa.Boolean(), nullable=True),
        sa.Column("covered_collection_in_vehicles", sa.Boolean(), nullable=True),
        sa.Column("waste_disposed_at_rrc", sa.Boolean(), nullable=True),
        sa.Column(
            "rrc_waste_collection_and_disposal_arrangement", sa.Boolean(), nullable=True
        ),
        sa.Column("waste_collection_vehicle_functional", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authority_users_block_id"),
        "authority_users",
        ["block_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authority_users_district_id"),
        "authority_users",
        ["district_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authority_users_village_id"),
        "authority_users",
        ["village_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_blocks_district_id"), "blocks", ["district_id"], unique=False
    )
    op.create_index(
        op.f("ix_complaint_type_geographical_ineligibilities_village_id"),
        "complaint_type_geographical_ineligibilities",
        ["village_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaints_village_id"), "complaints", ["village_id"], unique=False
    )
    op.create_index(
        op.f("ix_contractors_village_id"), "contractors", ["village_id"], unique=False
    )
    op.create_index(
        op.f("ix_inspections_village_id"), "inspections", ["village_id"], unique=False
    )
    op.create_index(
        op.f("ix_villages_block_id"), "villages", ["block_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_villages_block_id"), table_name="villages")
    op.drop_index(op.f("ix_inspections_village_id"), table_name="inspections")
    op.alter_column(
        "inspection_road_cleaning_inspection_items",
        "drain_cleaning_frequency",
        existing_type=sa.Enum(
            "WEEKLY", "FORTNIGHTLY", "MONTHLY", "NONE", name="draincleaningfrequency"
        ),
        type_=postgresql.ENUM(
            "WEEKLY", "FORTNIGHTLY", "MONTHLY", "NONE", name="drain_clean_freq"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "inspection_road_cleaning_inspection_items",
        "road_cleaning_frequency",
        existing_type=sa.Enum(
            "WEEKLY", "FORTNIGHTLY", "MONTHLY", "NONE", name="roadcleaningfrequency"
        ),
        type_=postgresql.ENUM(
            "WEEKLY", "FORTNIGHTLY", "MONTHLY", "NONE", name="road_clean_freq"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "inspection_community_sanitation_inspection_items",
        "csc_cleaning_frequency",
        existing_type=sa.Enum(
            "DAILY", "ONCE_IN_THREE_DAYS", "WEEKLY", "NONE", name="csccleaningfrequency"
        ),
        type_=postgresql.ENUM(
            "DAILY", "ONCE_IN_THREE_DAYS", "WEEKLY", "NONE", name="csc_clean_freq"
        ),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_contractors_village_id"), table_name="contractors")
    op.drop_index(op.f("ix_complaints_village_id"), table_name="complaints")
    op.drop_index(
        op.f("ix_complaint_type_geographical_ineligibilities_village_id"),
        table_name="complaint_type_geographical_ineligibilities",
    )
    op.drop_index(op.f("ix_blocks_district_id"), table_name="blocks")
    op.drop_index(op.f("ix_authority_users_village_id"), table_name="authority_users")
    op.drop_index(op.f("ix_authority_users_district_id"), table_name="authority_users")
    op.drop_index(op.f("ix_authority_users_block_id"), table_name="authority_users")
    op.create_table(
        "inspection_household_waste_collection_and_disposal_inspection_items",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "waste_collection_frequency",
            postgresql.ENUM(
                "DAILY", "ONCE_IN_THREE_DAYS", "WEEKLY", "NONE", name="waste_coll_freq"
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "dry_wet_vehicle_segregation",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "covered_collection_in_vehicles",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "waste_disposed_at_rrc", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rrc_waste_collection_and_disposal_arrangement",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "waste_collection_vehicle_functional",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
            name=op.f(
                "inspection_household_waste_collection_and_disposal_insp_id_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "inspection_household_waste_collection_and_disposal_inspect_pkey"
            ),
        ),
    )
    op.drop_table("inspection_household_waste_collection_and_disposal_inspection_items")
    # ### end Alembic commands ###
