"""make_volunteer_location_fields_nullable

Revision ID: 28a799226f06
Revises: 649d85f75325
Create Date: 2026-06-20 15:52:35.698356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a799226f06'
down_revision: Union[str, Sequence[str], None] = '649d85f75325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer_registrations', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('volunteer_registrations', 'gp_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('volunteer_registrations', 'village_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer_registrations', 'village_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volunteer_registrations', 'gp_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('volunteer_registrations', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
