"""change column names to gp id

Revision ID: 290bb1caed5c
Revises: 7f48b06b13d4
Create Date: 2025-10-22 13:19:37.767676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290bb1caed5c'
down_revision: Union[str, Sequence[str], None] = '7f48b06b13d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authority_users', sa.Column('gp_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_authority_users_village_id'), table_name='authority_users')
    op.drop_constraint(op.f('uix_user_geo'), 'authority_users', type_='unique')
    op.create_unique_constraint('uix_user_geo', 'authority_users', ['gp_id', 'block_id', 'district_id', 'username'])
    op.create_index(op.f('ix_authority_users_gp_id'), 'authority_users', ['gp_id'], unique=False)
    op.drop_constraint(op.f('authority_users_village_id_fkey'), 'authority_users', type_='foreignkey')
    op.create_foreign_key(None, 'authority_users', 'gram_panchayats', ['gp_id'], ['id'])
    op.drop_column('authority_users', 'village_id')
    op.add_column('complaints', sa.Column('gp_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_complaints_village_id'), table_name='complaints')
    op.create_index(op.f('ix_complaints_gp_id'), 'complaints', ['gp_id'], unique=False)
    op.drop_constraint(op.f('complaints_village_id_fkey'), 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'gram_panchayats', ['gp_id'], ['id'])
    op.drop_column('complaints', 'village_id')
    op.add_column('contractors', sa.Column('gp_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_contractors_village_id'), table_name='contractors')
    op.create_index(op.f('ix_contractors_gp_id'), 'contractors', ['gp_id'], unique=False)
    op.drop_constraint(op.f('contractors_village_id_fkey'), 'contractors', type_='foreignkey')
    op.create_foreign_key(None, 'contractors', 'gram_panchayats', ['gp_id'], ['id'])
    op.drop_column('contractors', 'village_id')
    op.add_column('inspections', sa.Column('gp_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_inspections_village_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_village_id_date'), table_name='inspections')
    op.create_index('ix_inspections_date_gp_id', 'inspections', ['date', 'gp_id'], unique=False)
    op.create_index('ix_inspections_gp_id', 'inspections', ['gp_id'], unique=False)
    op.drop_constraint(op.f('inspections_village_id_fkey'), 'inspections', type_='foreignkey')
    op.create_foreign_key(None, 'inspections', 'gram_panchayats', ['gp_id'], ['id'])
    op.drop_column('inspections', 'village_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('village_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.create_foreign_key(op.f('inspections_village_id_fkey'), 'inspections', 'gram_panchayats', ['village_id'], ['id'])
    op.drop_index('ix_inspections_gp_id', table_name='inspections')
    op.drop_index('ix_inspections_date_gp_id', table_name='inspections')
    op.create_index(op.f('ix_inspections_village_id_date'), 'inspections', ['village_id', 'date'], unique=False)
    op.create_index(op.f('ix_inspections_village_id'), 'inspections', ['village_id'], unique=False)
    op.drop_column('inspections', 'gp_id')
    op.add_column('contractors', sa.Column('village_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contractors', type_='foreignkey')
    op.create_foreign_key(op.f('contractors_village_id_fkey'), 'contractors', 'gram_panchayats', ['village_id'], ['id'])
    op.drop_index(op.f('ix_contractors_gp_id'), table_name='contractors')
    op.create_index(op.f('ix_contractors_village_id'), 'contractors', ['village_id'], unique=False)
    op.drop_column('contractors', 'gp_id')
    op.add_column('complaints', sa.Column('village_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key(op.f('complaints_village_id_fkey'), 'complaints', 'gram_panchayats', ['village_id'], ['id'])
    op.drop_index(op.f('ix_complaints_gp_id'), table_name='complaints')
    op.create_index(op.f('ix_complaints_village_id'), 'complaints', ['village_id'], unique=False)
    op.drop_column('complaints', 'gp_id')
    op.add_column('authority_users', sa.Column('village_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'authority_users', type_='foreignkey')
    op.create_foreign_key(op.f('authority_users_village_id_fkey'), 'authority_users', 'gram_panchayats', ['village_id'], ['id'])
    op.drop_index(op.f('ix_authority_users_gp_id'), table_name='authority_users')
    op.drop_constraint('uix_user_geo', 'authority_users', type_='unique')
    op.create_unique_constraint(op.f('uix_user_geo'), 'authority_users', ['village_id', 'block_id', 'district_id', 'username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_authority_users_village_id'), 'authority_users', ['village_id'], unique=False)
    op.drop_column('authority_users', 'gp_id')
    # ### end Alembic commands ###
