"""timestamps for complaint

Revision ID: 2ca7ae072c2e
Revises: 1b00c884998c
Create Date: 2025-10-24 17:18:32.616249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ca7ae072c2e"
down_revision: Union[str, Sequence[str], None] = "1b00c884998c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    op.add_column("complaints", sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("complaints", sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("complaints", sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complaints", "closed_at")
    op.drop_column("complaints", "verified_at")
    op.drop_column("complaints", "resolved_at")
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=False)
    # ### end Alembic commands ###
