"""Create coordinates in complaint

Revision ID: 2e59c36a1a91
Revises: d540cfe830f2
Create Date: 2025-10-11 23:06:33.704181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2e59c36a1a91"
down_revision: Union[str, Sequence[str], None] = "d540cfe830f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaints", sa.Column("lat", sa.Float(), server_default="0.0", nullable=False)
    )
    op.add_column(
        "complaints",
        sa.Column("long", sa.Float(), server_default="0.0", nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complaints", "long")
    op.drop_column("complaints", "lat")
