"""Allow Public Users to comment

Revision ID: 3a2adc91e493
Revises: b9ef3fc7724f
Create Date: 2025-09-25 18:19:48.711879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a2adc91e493'
down_revision: Union[str, Sequence[str], None] = 'b9ef3fc7724f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column('complaint_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('complaint_comments', sa.Column('mobile_number', sa.VARCHAR(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaint_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('complaint_comments', 'mobile_number')