"""Feedback model public user int type

Revision ID: 3cb1dee2532a
Revises: 84369513c7d1
Create Date: 2025-11-01 12:42:50.814589

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cb1dee2532a"
down_revision: Union[str, Sequence[str], None] = "84369513c7d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index("ix_annual_survey_financial_year_fy", "annual_survey_financial_year", ["fy"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_annual_survey_financial_year_fy", table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    # ### end Alembic commands ###
