"""add_d2d_active_field

Revision ID: 40760793639e
Revises: cd3f6b3b68a9
Create Date: 2026-04-05 21:59:59.415204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40760793639e'
down_revision: Union[str, Sequence[str], None] = 'cd3f6b3b68a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_d2d_activities', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_d2d_activities', 'is_active')
    # ### end Alembic commands ###
