"""Inspection models remove non required fields

Revision ID: 407a3e84028b
Revises: 96aa73d0db0f
Create Date: 2025-10-09 08:57:43.523460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407a3e84028b'
down_revision: Union[str, Sequence[str], None] = '96aa73d0db0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inspections_block_id_fkey'), 'inspections', type_='foreignkey')
    op.drop_constraint(op.f('inspections_district_id_fkey'), 'inspections', type_='foreignkey')
    op.drop_column('inspections', 'block_id')
    op.drop_column('inspections', 'district_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inspections', sa.Column('block_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('inspections_district_id_fkey'), 'inspections', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(op.f('inspections_block_id_fkey'), 'inspections', 'blocks', ['block_id'], ['id'])
    # ### end Alembic commands ###
