"""replace name by employee reference

Revision ID: 54d89d41b037
Revises: 123aa357f999
Create Date: 2025-10-31 16:48:02.157443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54d89d41b037"
down_revision: Union[str, Sequence[str], None] = "123aa357f999"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "authority_holder_persons", sa.Column("employee_id", sa.Integer(), server_default="1", nullable=False)
    )
    op.create_foreign_key(None, "authority_holder_persons", "employees", ["employee_id"], ["id"])
    op.drop_column("authority_holder_persons", "first_name")
    op.drop_column("authority_holder_persons", "last_name")
    op.drop_column("authority_holder_persons", "middle_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "authority_holder_persons", sa.Column("middle_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column("authority_holder_persons", sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column(
        "authority_holder_persons", sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "authority_holder_persons", type_="foreignkey")
    op.drop_column("authority_holder_persons", "employee_id")
    # ### end Alembic commands ###
