"""add_volunteer_registration

Revision ID: 58f326bc6aa1
Revises: 0060be78fb43
Create Date: 2026-06-16 10:16:34.580065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f326bc6aa1'
down_revision: Union[str, Sequence[str], None] = '0060be78fb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('aadhar_number', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('alternate_mobile', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('gp_id', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(), nullable=False),
    sa.Column('ward_number', sa.String(), nullable=True),
    sa.Column('full_address', sa.Text(), nullable=False),
    sa.Column('pin_code', sa.String(), nullable=False),
    sa.Column('highest_qualification', sa.String(), nullable=False),
    sa.Column('current_occupation', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('service_types', sa.JSON(), nullable=False),
    sa.Column('preferred_days', sa.JSON(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('commitment_duration', sa.String(), nullable=False),
    sa.Column('fitness_level', sa.String(), nullable=False),
    sa.Column('relevant_skills', sa.Text(), nullable=True),
    sa.Column('willing_to_work_other_villages', sa.Boolean(), nullable=False),
    sa.Column('can_bring_more_volunteers', sa.Boolean(), nullable=False),
    sa.Column('additional_volunteers_count', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['gp_id'], ['gram_panchayats.id'], ),
    sa.ForeignKeyConstraint(['public_user_id'], ['public_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_registrations_aadhar_number'), 'volunteer_registrations', ['aadhar_number'], unique=False)
    op.create_index(op.f('ix_volunteer_registrations_public_user_id'), 'volunteer_registrations', ['public_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_registrations_public_user_id'), table_name='volunteer_registrations')
    op.drop_index(op.f('ix_volunteer_registrations_aadhar_number'), table_name='volunteer_registrations')
    op.drop_table('volunteer_registrations')
    # ### end Alembic commands ###
