"""add_new_asset_components

Revision ID: 5b86dafe2385
Revises: 40760793639e
Create Date: 2026-06-11 09:18:05.516714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b86dafe2385'
down_revision: Union[str, Sequence[str], None] = '40760793639e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_bartan_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('established_banks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_vehicle_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owned_tricycles', sa.Integer(), nullable=False),
    sa.Column('owned_e_rickshaws', sa.Integer(), nullable=False),
    sa.Column('owned_motorized_vehicles', sa.Integer(), nullable=False),
    sa.Column('contractor_tricycles', sa.Integer(), nullable=False),
    sa.Column('contractor_e_rickshaws', sa.Integer(), nullable=False),
    sa.Column('contractor_motorized_vehicles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_annual_survey_financial_year_fy'), table_name='annual_survey_financial_year')
    op.create_index('ix_annual_survey_financial_year_fy', 'annual_survey_financial_year', ['fy'], unique=False)
    op.add_column('survey_d2d_activities', sa.Column('sanctioned_mixed_model', sa.Integer(), nullable=False))
    op.add_column('survey_gobardhan_projects', sa.Column('total_sanctioned', sa.Integer(), nullable=False))
    op.add_column('survey_gobardhan_projects', sa.Column('total_functional', sa.Integer(), nullable=False))
    op.add_column('survey_gobardhan_projects', sa.Column('gas_production', sa.Numeric(precision=15, scale=2), nullable=False))
    op.drop_column('survey_gobardhan_projects', 'total_projects')
    op.add_column('survey_swm_assets_new', sa.Column('hh_compost_pit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_swm_assets_new', 'hh_compost_pit')
    op.add_column('survey_gobardhan_projects', sa.Column('total_projects', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('survey_gobardhan_projects', 'gas_production')
    op.drop_column('survey_gobardhan_projects', 'total_functional')
    op.drop_column('survey_gobardhan_projects', 'total_sanctioned')
    op.drop_column('survey_d2d_activities', 'sanctioned_mixed_model')
    op.drop_index('ix_annual_survey_financial_year_fy', table_name='annual_survey_financial_year')
    op.create_index(op.f('ix_annual_survey_financial_year_fy'), 'annual_survey_financial_year', ['fy'], unique=True)
    op.drop_table('survey_vehicle_assets')
    op.drop_table('survey_bartan_banks')
    # ### end Alembic commands ###
