"""Include both VDO and worker as authorities

Revision ID: 635c02f3daee
Revises: 78faacbeabf5
Create Date: 2025-10-09 21:14:54.856465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635c02f3daee'
down_revision: Union[str, Sequence[str], None] = '78faacbeabf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_user_geo'), 'authority_users', type_='unique')
    op.create_unique_constraint('uix_user_geo', 'authority_users', ['village_id', 'block_id', 'district_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_geo', 'authority_users', type_='unique')
    op.create_unique_constraint(op.f('uix_user_geo'), 'authority_users', ['village_id', 'block_id', 'district_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
