"""add closed_by fields to complaint

Revision ID: 649d85f75325
Revises: 58f326bc6aa1
Create Date: 2026-06-16 22:29:20.464161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649d85f75325'
down_revision: Union[str, Sequence[str], None] = '58f326bc6aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('closed_by_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('closed_by_info', sa.String(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'authority_users', ['closed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'closed_by_info')
    op.drop_column('complaints', 'closed_by_id')
    # ### end Alembic commands ###
