"""event model

Revision ID: 76865e89aa5d
Revises: 9b8edd20eb92
Create Date: 2025-09-27 16:34:13.046937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "76865e89aa5d"
down_revision: Union[str, Sequence[str], None] = "9b8edd20eb92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('events_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), autoincrement=False, nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), autoincrement=False, nullable=False),
        sa.Column("active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="events_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "event_media",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("media_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("event_media_pkey")),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], name=op.f("event_media_event_id_fkey")),
        postgresql_ignore_search_path=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_media")
    op.drop_table("events")
