"""unique name type for notices

Revision ID: 773e502883d8
Revises: 7bb021ad1202
Create Date: 2025-10-31 06:45:13.596594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "773e502883d8"
down_revision: Union[str, Sequence[str], None] = "7bb021ad1202"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_notice_type_name", "notice_types", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_notice_type_name", "notice_types", type_="unique")
    # ### end Alembic commands ###
