"""Attendance Parameters

Revision ID: 78c12eebb01a
Revises: 08729624e5bc
Create Date: 2025-09-29 15:56:18.317053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78c12eebb01a'
down_revision: Union[str, Sequence[str], None] = '08729624e5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendances",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("contractor_id", sa.Integer(), nullable=False),
        sa.Column("village_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("start_lat", sa.String(), nullable=False),
        sa.Column("start_long", sa.String(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("end_lat", sa.String(), nullable=True),
        sa.Column("end_long", sa.String(), nullable=True),
        sa.Column("remarks", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"]),
        sa.ForeignKeyConstraint(["village_id"], ["villages.id"]),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attendances")