"""Unique User Role Constraint on User and not Position Holder

Revision ID: 78faacbeabf5
Revises: 9ad7e7dfde67
Create Date: 2025-10-09 18:48:45.409838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78faacbeabf5"
down_revision: Union[str, Sequence[str], None] = "9ad7e7dfde67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uix_role_geo"), "authority_holder_persons", type_="unique")
    op.create_unique_constraint(
        "uix_user_geo", "authority_users", ["village_id", "block_id", "district_id"]
    )
    op.drop_constraint(op.f("notices_receiver_id_fkey"), "notices", type_="foreignkey")
    op.drop_constraint(op.f("notices_sender_id_fkey"), "notices", type_="foreignkey")
    op.create_foreign_key(
        None, "notices", "authority_holder_persons", ["sender_id"], ["id"]
    )
    op.create_foreign_key(
        None, "notices", "authority_holder_persons", ["receiver_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notices", type_="foreignkey")
    op.drop_constraint(None, "notices", type_="foreignkey")
    op.create_foreign_key(
        op.f("notices_sender_id_fkey"),
        "notices",
        "authority_users",
        ["sender_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("notices_receiver_id_fkey"),
        "notices",
        "authority_users",
        ["receiver_id"],
        ["id"],
    )
    op.drop_constraint("uix_user_geo", "authority_users", type_="unique")
    op.create_unique_constraint(
        op.f("uix_role_geo"),
        "authority_holder_persons",
        ["role_id", "village_id", "block_id", "district_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
