"""GPS tracking record by vehicle

Revision ID: 798647eaf936
Revises: eb275f7a113e
Create Date: 2025-11-02 17:16:12.144733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798647eaf936'
down_revision: Union[str, Sequence[str], None] = 'eb275f7a113e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('ignition', sa.Boolean(), nullable=False),
    sa.Column('total_gps_odometer', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gps_record_timestamp', 'gps_records', ['timestamp'], unique=False)
    op.create_index('idx_gps_record_vehicle', 'gps_records', ['vehicle_id'], unique=False)
    op.create_index('idx_gps_record_vehicle_timestamp', 'gps_records', ['vehicle_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_gps_records_timestamp'), 'gps_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_gps_records_vehicle_id'), 'gps_records', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gps_records_vehicle_id'), table_name='gps_records')
    op.drop_index(op.f('ix_gps_records_timestamp'), table_name='gps_records')
    op.drop_index('idx_gps_record_vehicle_timestamp', table_name='gps_records')
    op.drop_index('idx_gps_record_vehicle', table_name='gps_records')
    op.drop_index('idx_gps_record_timestamp', table_name='gps_records')
    op.drop_table('gps_records')
    # ### end Alembic commands ###
