"""Add geo indicators to user accounts

Revision ID: 7aaa006cd64e
Revises: 407a3e84028b
Create Date: 2025-10-09 17:30:03.371735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aaa006cd64e'
down_revision: Union[str, Sequence[str], None] = '407a3e84028b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authority_users', sa.Column('village_id', sa.Integer(), nullable=True))
    op.add_column('authority_users', sa.Column('block_id', sa.Integer(), nullable=True))
    op.add_column('authority_users', sa.Column('district_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'authority_users', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(None, 'authority_users', 'villages', ['village_id'], ['id'])
    op.create_foreign_key(None, 'authority_users', 'blocks', ['block_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authority_users', type_='foreignkey')
    op.drop_constraint(None, 'authority_users', type_='foreignkey')
    op.drop_constraint(None, 'authority_users', type_='foreignkey')
    op.drop_column('authority_users', 'district_id')
    op.drop_column('authority_users', 'block_id')
    op.drop_column('authority_users', 'village_id')
    # ### end Alembic commands ###
