"""notice type for notices

Revision ID: 7bb021ad1202
Revises: 06746a9e7bbe
Create Date: 2025-10-31 06:40:50.468503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bb021ad1202"
down_revision: Union[str, Sequence[str], None] = "06746a9e7bbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notice_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("notices", sa.Column("type_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "notices", "notice_types", ["type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notices", type_="foreignkey")
    op.drop_column("notices", "type_id")
    op.drop_table("notice_types")
    # ### end Alembic commands ###
