"""add_sla_tracking_fields

Revision ID: 7d066c6ff805
Revises: 5b86dafe2385
Create Date: 2026-06-14 22:23:56.125359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d066c6ff805'
down_revision: Union[str, Sequence[str], None] = '5b86dafe2385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annual_survey_financial_year_fy'), table_name='annual_survey_financial_year')
    op.create_index(op.f('ix_annual_survey_financial_year_fy'), 'annual_survey_financial_year', ['fy'], unique=True)
    op.add_column('complaint_comments', sa.Column('is_system_generated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('complaints', sa.Column('last_sla_breach_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'last_sla_breach_level')
    op.drop_column('complaint_comments', 'is_system_generated')
    op.drop_index(op.f('ix_annual_survey_financial_year_fy'), table_name='annual_survey_financial_year')
    op.create_index(op.f('ix_annual_survey_financial_year_fy'), 'annual_survey_financial_year', ['fy'], unique=False)
    # ### end Alembic commands ###
