"""reinit

Revision ID: 7f48b06b13d4
Revises:
Create Date: 2025-10-19 19:16:02.925715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f48b06b13d4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "complaint_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "complaint_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "districts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "public_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("mobile_number", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_public_users_mobile_number"), "public_users", ["mobile_number"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "schemes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("eligibility", sa.String(), nullable=True),
        sa.Column("benefits", sa.String(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schemes_id"), "schemes", ["id"], unique=False)
    op.create_table(
        "survey_questions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("form_question_group", sa.String(), nullable=True),
        sa.Column("form_question_group_question_id", sa.String(), nullable=True),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blocks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "district_id", name="uq_block_name_district"),
    )
    op.create_index(op.f("ix_blocks_district_id"), "blocks", ["district_id"], unique=False)
    op.create_table(
        "event_media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("media_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_media_event_id"), "event_media", ["event_id"], unique=False)
    op.create_table(
        "public_user_device_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_user_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("fcm_token", sa.String(), nullable=False),
        sa.Column("device_name", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["public_user_id"], ["public_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_user_id", "device_id", name="uq_public_user_device"),
    )
    op.create_table(
        "public_user_otps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_user_id", sa.Integer(), nullable=False),
        sa.Column("otp", sa.String(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["public_user_id"],
            ["public_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_public_user_otps_public_user_id"), "public_user_otps", ["public_user_id"], unique=False)
    op.create_table(
        "public_user_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("expires_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["public_user_id"],
            ["public_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_public_user_tokens_public_user_id"), "public_user_tokens", ["public_user_id"], unique=False
    )
    op.create_table(
        "scheme_media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scheme_id", sa.Integer(), nullable=False),
        sa.Column("media_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["schemes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scheme_media_id"), "scheme_media", ["id"], unique=False)
    op.create_table(
        "gram_panchayats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_gram_panchayat_block", "gram_panchayats", ["block_id"], unique=False)
    op.create_index("ix_gram_panchayat_name", "gram_panchayats", ["name"], unique=False)
    op.create_index(op.f("ix_gram_panchayats_block_id"), "gram_panchayats", ["block_id"], unique=False)
    op.create_index(op.f("ix_gram_panchayats_name"), "gram_panchayats", ["name"], unique=False)
    op.create_table(
        "authority_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("village_id", sa.Integer(), nullable=True),
        sa.Column("block_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["gram_panchayats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("village_id", "block_id", "district_id", "username", name="uix_user_geo"),
    )
    op.create_index(op.f("ix_authority_users_block_id"), "authority_users", ["block_id"], unique=False)
    op.create_index(op.f("ix_authority_users_district_id"), "authority_users", ["district_id"], unique=False)
    op.create_index(op.f("ix_authority_users_username"), "authority_users", ["username"], unique=True)
    op.create_index(op.f("ix_authority_users_village_id"), "authority_users", ["village_id"], unique=False)
    op.create_table(
        "complaint_type_geographical_ineligibilities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("complaint_type_id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("block_id", sa.Integer(), nullable=True),
        sa.Column("village_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["complaint_type_id"],
            ["complaint_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["gram_panchayats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_complaint_type_geographical_ineligibilities_village_id"),
        "complaint_type_geographical_ineligibilities",
        ["village_id"],
        unique=False,
    )
    op.create_table(
        "complaints",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("complaint_type_id", sa.Integer(), nullable=False),
        sa.Column("village_id", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("mobile_number", sa.String(), nullable=True),
        sa.Column("public_user_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("long", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["complaint_type_id"],
            ["complaint_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["public_user_id"],
            ["public_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["complaint_statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["gram_panchayats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_complaints_village_id"), "complaints", ["village_id"], unique=False)
    op.create_table(
        "contractors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("person_name", sa.String(), nullable=True),
        sa.Column("person_phone", sa.String(), nullable=True),
        sa.Column("village_id", sa.Integer(), nullable=False),
        sa.Column("contract_start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contract_end_date", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["gram_panchayats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contractors_village_id"), "contractors", ["village_id"], unique=False)
    op.create_table(
        "villages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("gp_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gp_id"],
            ["gram_panchayats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "gp_id", name="uq_village_name_gp"),
    )
    op.create_index("ix_village_name_gp", "villages", ["name", "gp_id"], unique=False)
    op.create_index(op.f("ix_villages_gp_id"), "villages", ["gp_id"], unique=False)
    op.create_index(op.f("ix_villages_name"), "villages", ["name"], unique=False)
    op.create_table(
        "authority_holder_persons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("gp_id", sa.Integer(), nullable=True),
        sa.Column("block_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("middle_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("date_of_joining", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["authority_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["gram_panchayats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "complaint_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("complaint_id IS NOT NULL AND user_id IS NOT NULL", name="complaint_user_not_null"),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["authority_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("complaint_id", "user_id", name="complaint_user_unique"),
    )
    op.create_table(
        "complaint_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("mobile_number", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("commented_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["authority_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "complaint_media",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=False),
        sa.Column("media_url", sa.String(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_by_public_mobile", sa.String(), nullable=True),
        sa.Column("uploaded_by_user_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "uploaded_by_public_mobile IS NOT NULL OR uploaded_by_user_id IS NOT NULL", name="uploaded_by_constraint"
        ),
        sa.CheckConstraint(
            "uploaded_by_public_mobile IS NULL OR uploaded_by_user_id IS NULL",
            name="uploaded_by_exclusivity_constraint",
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["authority_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contractor_attendances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contractor_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("start_lat", sa.String(), nullable=False),
        sa.Column("start_long", sa.String(), nullable=False),
        sa.Column("end_lat", sa.String(), nullable=True),
        sa.Column("end_long", sa.String(), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remarks", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contractor_id"],
            ["contractors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_form_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to", sa.Integer(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["authority_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["authority_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_forms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["authority_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["authority_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_question_options",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column(
            "answer_type",
            sa.Enum(
                "TEXT", "NUMBER", "DATE", "DATETIME", "BOOLEAN", "SINGLE_CHOICE", "MULTIPLE_CHOICE", name="answertype"
            ),
            nullable=False,
        ),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["authority_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["survey_questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["authority_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_question_responses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("submitted_by", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submission_notes", sa.String(), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("review_notes", sa.String(), nullable=True),
        sa.Column(
            "status", sa.Enum("PENDING", "REVIEWED", "APPROVED", "REJECTED", name="responsereviewstatus"), nullable=True
        ),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["authority_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["authority_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["authority_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_device_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("fcm_token", sa.String(), nullable=False),
        sa.Column("device_name", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["authority_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "device_id", name="uq_user_device"),
    )
    op.create_table(
        "annual_surveys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gp_id", sa.Integer(), nullable=False),
        sa.Column("survey_date", sa.Date(), nullable=False),
        sa.Column("vdo_id", sa.Integer(), nullable=False),
        sa.Column("sarpanch_name", sa.String(length=255), nullable=True),
        sa.Column("sarpanch_contact", sa.String(length=20), nullable=True),
        sa.Column("num_ward_panchs", sa.Integer(), nullable=True),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gp_id"],
            ["gram_panchayats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vdo_id"],
            ["authority_holder_persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_annual_surveys_gp_id"), "annual_surveys", ["gp_id"], unique=False)
    op.create_index("ix_annual_surveys_gp_id_survey_date", "annual_surveys", ["gp_id", "survey_date"], unique=False)
    op.create_index(op.f("ix_annual_surveys_survey_date"), "annual_surveys", ["survey_date"], unique=False)
    op.create_table(
        "inspections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("remarks", sa.String(), nullable=True),
        sa.Column("position_holder_id", sa.Integer(), nullable=False),
        sa.Column("village_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lat", sa.String(), nullable=False),
        sa.Column("long", sa.String(), nullable=False),
        sa.Column("register_maintenance", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_holder_id"],
            ["authority_holder_persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["gram_panchayats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inspections_date"), "inspections", ["date"], unique=False)
    op.create_index("ix_inspections_village_id", "inspections", ["village_id"], unique=False)
    op.create_index("ix_inspections_village_id_date", "inspections", ["village_id", "date"], unique=False)
    op.create_table(
        "notices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("receiver_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["authority_holder_persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["authority_holder_persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_community_sanitation_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "csc_cleaning_frequency",
            sa.Enum("DAILY", "ONCE_IN_THREE_DAYS", "WEEKLY", "NONE", name="csc_clean_freq"),
            nullable=True,
        ),
        sa.Column("electricity_and_water", sa.Boolean(), nullable=True),
        sa.Column("csc_used_by_community", sa.Boolean(), nullable=True),
        sa.Column("pink_toilets_cleaning", sa.Boolean(), nullable=True),
        sa.Column("pink_toilets_used", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_household_waste_collection_and_disposal_inspection_i",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "waste_collection_frequency",
            sa.Enum("DAILY", "ONCE_IN_THREE_DAYS", "WEEKLY", "NONE", name="waste_coll_freq"),
            nullable=True,
        ),
        sa.Column("dry_wet_vehicle_segregation", sa.Boolean(), nullable=True),
        sa.Column("covered_collection_in_vehicles", sa.Boolean(), nullable=True),
        sa.Column("waste_disposed_at_rrc", sa.Boolean(), nullable=True),
        sa.Column("rrc_waste_collection_and_disposal_arrangement", sa.Boolean(), nullable=True),
        sa.Column("waste_collection_vehicle_functional", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("inspection_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_other_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firm_paid_regularly", sa.Boolean(), nullable=True),
        sa.Column("cleaning_staff_paid_regularly", sa.Boolean(), nullable=True),
        sa.Column("firm_provided_safety_equipment", sa.Boolean(), nullable=True),
        sa.Column("regular_feedback_register_entry", sa.Boolean(), nullable=True),
        sa.Column("chart_prepared_for_cleaning_work", sa.Boolean(), nullable=True),
        sa.Column("village_visibly_clean", sa.Boolean(), nullable=True),
        sa.Column("rate_chart_displayed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_road_cleaning_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "road_cleaning_frequency",
            sa.Enum("WEEKLY", "FORTNIGHTLY", "MONTHLY", "NONE", name="road_clean_freq"),
            nullable=True,
        ),
        sa.Column(
            "drain_cleaning_frequency",
            sa.Enum("WEEKLY", "FORTNIGHTLY", "MONTHLY", "NONE", name="drain_clean_freq"),
            nullable=True,
        ),
        sa.Column("disposal_of_sludge_from_drains", sa.Boolean(), nullable=True),
        sa.Column("drain_waste_colllected_on_roadside", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notice_media",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("media_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_csc_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numbers", sa.Integer(), nullable=True),
        sa.Column(
            "cleaning_frequency",
            sa.Enum(
                "DAILY",
                "ALTERNATE_DAYS",
                "TWICE_A_WEEK",
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "NONE",
                name="csc_cleaning_frequency",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_door_to_door_collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("num_households", sa.Integer(), nullable=True),
        sa.Column("num_shops", sa.Integer(), nullable=True),
        sa.Column(
            "collection_frequency",
            sa.Enum(
                "DAILY", "ALTERNATE_DAYS", "TWICE_A_WEEK", "WEEKLY", "FORTNIGHTLY", "NONE", name="collection_frequency"
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_drain_cleaning",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("length", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "cleaning_frequency",
            sa.Enum(
                "DAILY",
                "ALTERNATE_DAYS",
                "TWICE_A_WEEK",
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "NONE",
                name="drain_cleaning_frequency",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_fund_sanctioned",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("head", sa.Enum("FFC", "SFC", "CSR", "OWN_INCOME", "OTHER", name="fund_head"), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_road_sweeping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("width", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("length", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "cleaning_frequency",
            sa.Enum(
                "DAILY",
                "ALTERNATE_DAYS",
                "TWICE_A_WEEK",
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "NONE",
                name="road_cleaning_frequency",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_sbmg_year_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ihhl", sa.Integer(), nullable=True),
        sa.Column("csc", sa.Integer(), nullable=True),
        sa.Column("rrc", sa.Integer(), nullable=True),
        sa.Column("pwmu", sa.Integer(), nullable=True),
        sa.Column("soak_pit", sa.Integer(), nullable=True),
        sa.Column("magic_pit", sa.Integer(), nullable=True),
        sa.Column("leach_pit", sa.Integer(), nullable=True),
        sa.Column("wsp", sa.Integer(), nullable=True),
        sa.Column("dewats", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_swm_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rrc", sa.Integer(), nullable=True),
        sa.Column("pwmu", sa.Integer(), nullable=True),
        sa.Column("compost_pit", sa.Integer(), nullable=True),
        sa.Column("collection_vehicle", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_village_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("village_id", sa.Integer(), nullable=False),
        sa.Column("village_name", sa.String(length=255), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("num_households", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["survey_id"],
            ["annual_surveys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["villages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_survey_village_data_survey_id"), "survey_village_data", ["survey_id"], unique=False)
    op.create_index(op.f("ix_survey_village_data_village_id"), "survey_village_data", ["village_id"], unique=False)
    op.create_table(
        "survey_work_order_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_order_no", sa.String(length=100), nullable=True),
        sa.Column("work_order_date", sa.Date(), nullable=True),
        sa.Column("work_order_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["annual_surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_village_gwm_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("soak_pit", sa.Integer(), nullable=True),
        sa.Column("magic_pit", sa.Integer(), nullable=True),
        sa.Column("leach_pit", sa.Integer(), nullable=True),
        sa.Column("wsp", sa.Integer(), nullable=True),
        sa.Column("dewats", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["survey_village_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_village_sbmg_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ihhl", sa.Integer(), nullable=True),
        sa.Column("csc", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["survey_village_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("survey_village_sbmg_assets")
    op.drop_table("survey_village_gwm_assets")
    op.drop_table("survey_work_order_details")
    op.drop_index(op.f("ix_survey_village_data_village_id"), table_name="survey_village_data")
    op.drop_index(op.f("ix_survey_village_data_survey_id"), table_name="survey_village_data")
    op.drop_table("survey_village_data")
    op.drop_table("survey_swm_assets")
    op.drop_table("survey_sbmg_year_targets")
    op.drop_table("survey_road_sweeping")
    op.drop_table("survey_fund_sanctioned")
    op.drop_table("survey_drain_cleaning")
    op.drop_table("survey_door_to_door_collection")
    op.drop_table("survey_csc_details")
    op.drop_table("notice_media")
    op.drop_table("inspection_road_cleaning_inspection_items")
    op.drop_table("inspection_other_inspection_items")
    op.drop_table("inspection_images")
    op.drop_table("inspection_household_waste_collection_and_disposal_inspection_i")
    op.drop_table("inspection_community_sanitation_inspection_items")
    op.drop_table("notices")
    op.drop_index("ix_inspections_village_id_date", table_name="inspections")
    op.drop_index("ix_inspections_village_id", table_name="inspections")
    op.drop_index(op.f("ix_inspections_date"), table_name="inspections")
    op.drop_table("inspections")
    op.drop_index(op.f("ix_annual_surveys_survey_date"), table_name="annual_surveys")
    op.drop_index("ix_annual_surveys_gp_id_survey_date", table_name="annual_surveys")
    op.drop_index(op.f("ix_annual_surveys_gp_id"), table_name="annual_surveys")
    op.drop_table("annual_surveys")
    op.drop_table("user_device_tokens")
    op.drop_table("survey_question_responses")
    op.drop_table("survey_question_options")
    op.drop_table("survey_forms")
    op.drop_table("survey_form_assignments")
    op.drop_table("contractor_attendances")
    op.drop_table("complaint_media")
    op.drop_table("complaint_comments")
    op.drop_table("complaint_assignments")
    op.drop_table("authority_holder_persons")
    op.drop_index(op.f("ix_villages_name"), table_name="villages")
    op.drop_index(op.f("ix_villages_gp_id"), table_name="villages")
    op.drop_index("ix_village_name_gp", table_name="villages")
    op.drop_table("villages")
    op.drop_index(op.f("ix_contractors_village_id"), table_name="contractors")
    op.drop_table("contractors")
    op.drop_index(op.f("ix_complaints_village_id"), table_name="complaints")
    op.drop_table("complaints")
    op.drop_index(
        op.f("ix_complaint_type_geographical_ineligibilities_village_id"),
        table_name="complaint_type_geographical_ineligibilities",
    )
    op.drop_table("complaint_type_geographical_ineligibilities")
    op.drop_index(op.f("ix_authority_users_village_id"), table_name="authority_users")
    op.drop_index(op.f("ix_authority_users_username"), table_name="authority_users")
    op.drop_index(op.f("ix_authority_users_district_id"), table_name="authority_users")
    op.drop_index(op.f("ix_authority_users_block_id"), table_name="authority_users")
    op.drop_table("authority_users")
    op.drop_index(op.f("ix_gram_panchayats_name"), table_name="gram_panchayats")
    op.drop_index(op.f("ix_gram_panchayats_block_id"), table_name="gram_panchayats")
    op.drop_index("ix_gram_panchayat_name", table_name="gram_panchayats")
    op.drop_index("ix_gram_panchayat_block", table_name="gram_panchayats")
    op.drop_table("gram_panchayats")
    op.drop_index(op.f("ix_scheme_media_id"), table_name="scheme_media")
    op.drop_table("scheme_media")
    op.drop_index(op.f("ix_public_user_tokens_public_user_id"), table_name="public_user_tokens")
    op.drop_table("public_user_tokens")
    op.drop_index(op.f("ix_public_user_otps_public_user_id"), table_name="public_user_otps")
    op.drop_table("public_user_otps")
    op.drop_table("public_user_device_tokens")
    op.drop_index(op.f("ix_event_media_event_id"), table_name="event_media")
    op.drop_table("event_media")
    op.drop_index(op.f("ix_blocks_district_id"), table_name="blocks")
    op.drop_table("blocks")
    op.drop_table("survey_questions")
    op.drop_index(op.f("ix_schemes_id"), table_name="schemes")
    op.drop_table("schemes")
    op.drop_table("roles")
    op.drop_index(op.f("ix_public_users_mobile_number"), table_name="public_users")
    op.drop_table("public_users")
    op.drop_table("events")
    op.drop_table("districts")
    op.drop_table("complaint_types")
    op.drop_table("complaint_statuses")
    op.drop_table("agencies")
    # ### end Alembic commands ###
