"""assign one complaint to only one contractor

Revision ID: 8463d57f246e
Revises: 635c02f3daee
Create Date: 2025-10-10 20:43:10.206811

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8463d57f246e"
down_revision: Union[str, Sequence[str], None] = "635c02f3daee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("complaint_user_unique", "complaint_assignments", ["complaint_id", "user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("complaint_user_unique", "complaint_assignments", type_="unique")
    # ### end Alembic commands ###
