"""vehicle name field

Revision ID: 848cc179e059
Revises: 798647eaf936
Create Date: 2025-11-02 20:04:08.954684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "848cc179e059"
down_revision: Union[str, Sequence[str], None] = "798647eaf936"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    op.add_column("vehicles", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicles", "name")
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=False)
    # ### end Alembic commands ###
