"""One Survey per GP per FY

Revision ID: 8552eca07acc
Revises: f621e77d41e1
Create Date: 2025-10-24 08:56:15.126583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8552eca07acc'
down_revision: Union[str, Sequence[str], None] = 'f621e77d41e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_annual_survey_fy_gp', 'annual_surveys', ['fy_id', 'gp_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_annual_survey_fy_gp', 'annual_surveys', type_='unique')
    # ### end Alembic commands ###
