"""add public user bookmarks

Revision ID: 890c658e3b42
Revises: b1d34efc3126
Create Date: 2026-01-26 17:19:39.416561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "890c658e3b42"
down_revision: Union[str, Sequence[str], None] = "b1d34efc3126"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_annual_survey_financial_year_fy"),
        table_name="annual_survey_financial_year",
    )
    op.create_index(
        "ix_annual_survey_financial_year_fy",
        "annual_survey_financial_year",
        ["fy"],
        unique=False,
    )
    op.add_column(
        "event_bookmarks", sa.Column("public_user_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "event_bookmarks", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_index(
        op.f("ix_event_bookmarks_public_user_id"),
        "event_bookmarks",
        ["public_user_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uix_event_public_user_bookmark",
        "event_bookmarks",
        ["event_id", "public_user_id"],
    )
    op.create_foreign_key(
        "fk_event_bookmarks_public_users",
        "event_bookmarks",
        "public_users",
        ["public_user_id"],
        ["id"],
    )
    op.create_check_constraint(
        "check_event_bookmark_owner",
        "event_bookmarks",
        "(user_id IS NOT NULL AND public_user_id IS NULL) OR (user_id IS NULL AND public_user_id IS NOT NULL)",
    )

    op.add_column(
        "scheme_bookmarks", sa.Column("public_user_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "scheme_bookmarks", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_index(
        op.f("ix_scheme_bookmarks_public_user_id"),
        "scheme_bookmarks",
        ["public_user_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uix_scheme_public_user_bookmark",
        "scheme_bookmarks",
        ["scheme_id", "public_user_id"],
    )
    op.create_foreign_key(
        "fk_scheme_bookmarks_public_users",
        "scheme_bookmarks",
        "public_users",
        ["public_user_id"],
        ["id"],
    )
    op.create_check_constraint(
        "check_scheme_bookmark_owner",
        "scheme_bookmarks",
        "(user_id IS NOT NULL AND public_user_id IS NULL) OR (user_id IS NULL AND public_user_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_scheme_bookmark_owner", "scheme_bookmarks", type_="check")
    op.drop_constraint(
        "fk_scheme_bookmarks_public_users", "scheme_bookmarks", type_="foreignkey"
    )
    op.drop_constraint(
        "uix_scheme_public_user_bookmark", "scheme_bookmarks", type_="unique"
    )
    op.drop_index(
        op.f("ix_scheme_bookmarks_public_user_id"), table_name="scheme_bookmarks"
    )
    op.alter_column(
        "scheme_bookmarks", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("scheme_bookmarks", "public_user_id")

    op.drop_constraint("check_event_bookmark_owner", "event_bookmarks", type_="check")
    op.drop_constraint(
        "fk_event_bookmarks_public_users", "event_bookmarks", type_="foreignkey"
    )
    op.drop_constraint(
        "uix_event_public_user_bookmark", "event_bookmarks", type_="unique"
    )
    op.drop_index(
        op.f("ix_event_bookmarks_public_user_id"), table_name="event_bookmarks"
    )
    op.alter_column(
        "event_bookmarks", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("event_bookmarks", "public_user_id")
    op.drop_index(
        "ix_annual_survey_financial_year_fy", table_name="annual_survey_financial_year"
    )
    op.create_index(
        op.f("ix_annual_survey_financial_year_fy"),
        "annual_survey_financial_year",
        ["fy"],
        unique=True,
    )
    # ### end Alembic commands ###
