"""notice receiver is non nullable

Revision ID: 90c2ffc3dbd0
Revises: 773e502883d8
Create Date: 2025-10-31 07:15:53.711784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90c2ffc3dbd0"
down_revision: Union[str, Sequence[str], None] = "773e502883d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index("ix_annual_survey_financial_year_fy", "annual_survey_financial_year", ["fy"], unique=False)
    op.alter_column("notices", "receiver_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notices", "receiver_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_index("ix_annual_survey_financial_year_fy", table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    # ### end Alembic commands ###
