"""Inspection models

Revision ID: 96aa73d0db0f
Revises: 8ebe3c5d397e
Create Date: 2025-10-09 08:54:06.566836

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96aa73d0db0f"
down_revision: Union[str, Sequence[str], None] = "8ebe3c5d397e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community_sanitation_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "csc_cleaning_frequency",
            sa.Enum(
                "DAILY",
                "ONCE_IN_THREE_DAYS",
                "WEEKLY",
                "NONE",
                name="csccleaningfrequency",
            ),
            nullable=True,
        ),
        sa.Column("electricity_and_water", sa.Boolean(), nullable=True),
        sa.Column("csc_used_by_community", sa.Boolean(), nullable=True),
        sa.Column("pink_toilets_cleaning", sa.Boolean(), nullable=True),
        sa.Column("pink_toilets_used", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "household_waste_collection_and_disposal_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "waste_collection_frequency",
            sa.Enum(
                "DAILY",
                "ONCE_IN_THREE_DAYS",
                "WEEKLY",
                "NONE",
                name="wastecollectionfrequency",
            ),
            nullable=True,
        ),
        sa.Column("dry_wet_vehicle_segregation", sa.Boolean(), nullable=True),
        sa.Column("covered_collection_in_vehicles", sa.Boolean(), nullable=True),
        sa.Column("waste_disposed_at_rrc", sa.Boolean(), nullable=True),
        sa.Column(
            "rrc_waste_collection_and_disposal_arrangement", sa.Boolean(), nullable=True
        ),
        sa.Column("waste_collection_vehicle_functional", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "other_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firm_paid_regularly", sa.Boolean(), nullable=True),
        sa.Column("cleaning_staff_paid_regularly", sa.Boolean(), nullable=True),
        sa.Column("firm_provided_safety_equipment", sa.Boolean(), nullable=True),
        sa.Column("regular_feedback_register_entry", sa.Boolean(), nullable=True),
        sa.Column("chart_prepared_for_cleaning_work", sa.Boolean(), nullable=True),
        sa.Column("village_visibly_clean", sa.Boolean(), nullable=True),
        sa.Column("rate_chart_displayed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "road_cleaning_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "road_cleaning_frequency",
            sa.Enum(
                "WEEKLY", "FORTNIGHTLY", "MONTHLY", "NONE", name="roadcleaningfrequency"
            ),
            nullable=True,
        ),
        sa.Column(
            "drain_cleaning_frequency",
            sa.Enum(
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "NONE",
                name="draincleaningfrequency",
            ),
            nullable=True,
        ),
        sa.Column("disposal_of_sludge_from_drains", sa.Boolean(), nullable=True),
        sa.Column("drain_waste_colllected_on_roadside", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "inspections", sa.Column("register_maintenance", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inspections", "register_maintenance")
    op.drop_table("road_cleaning_inspection_items")
    op.drop_table("other_inspection_items")
    op.drop_table("household_waste_collection_and_disposal_inspection_items")
    op.drop_table("community_sanitation_inspection_items")
    # ### end Alembic commands ###
