"""Unique User Role Constraint

Revision ID: 9ad7e7dfde67
Revises: bc239ba9e199
Create Date: 2025-10-09 18:42:59.807388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ad7e7dfde67"
down_revision: Union[str, Sequence[str], None] = "bc239ba9e199"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_role_geo",
        "authority_holder_persons",
        ["role_id", "village_id", "block_id", "district_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_role_geo", "authority_holder_persons", type_="unique")
    # ### end Alembic commands ###
