"""add_work_frequency_to_d2d

Revision ID: a6828fa9b4f1
Revises: b84ff5c64092
Create Date: 2026-06-22 11:00:10.352968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6828fa9b4f1'
down_revision: Union[str, Sequence[str], None] = 'b84ff5c64092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    work_frequency_enum = sa.Enum('none', 'weekly', '15 days', 'monthly', name='work_frequency')
    work_frequency_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('survey_d2d_activities', sa.Column('work_frequency', work_frequency_enum, server_default='none', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_d2d_activities', 'work_frequency')
    work_frequency_enum = sa.Enum('none', 'weekly', '15 days', 'monthly', name='work_frequency')
    work_frequency_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
