"""Make contractor village id as a non nullable field

Revision ID: b83ca5c094e9
Revises: 14571a14cd51
Create Date: 2025-10-16 21:53:11.351539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b83ca5c094e9"
down_revision: Union[str, Sequence[str], None] = "14571a14cd51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contractors", "village_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contractors", "village_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
