"""contractor id to complaint assignment

Revision ID: b9d6b23e259c
Revises: 2ca7ae072c2e
Create Date: 2025-10-24 17:54:14.639966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9d6b23e259c"
down_revision: Union[str, Sequence[str], None] = "2ca7ae072c2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("complaint_assignments", sa.Column("contractor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "complaint_assignments", "contractors", ["contractor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "complaint_assignments", type_="foreignkey")
    op.drop_column("complaint_assignments", "contractor_id")
    # ### end Alembic commands ###
