"""Public User Token

Revision ID: b9ef3fc7724f
Revises: f41ac9a94d44
Create Date: 2025-09-25 17:37:29.923271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9ef3fc7724f'
down_revision: Union[str, Sequence[str], None] = 'f41ac9a94d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_user_tokens',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('public_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['public_user_id'], ['public_users.id'], name=op.f('public_user_tokens_public_user_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('public_user_tokens_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_user_tokens')