"""Update sender and receiver models

Revision ID: bc239ba9e199
Revises: 7aaa006cd64e
Create Date: 2025-10-09 18:35:26.990658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc239ba9e199"
down_revision: Union[str, Sequence[str], None] = "7aaa006cd64e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("notices_sender_id_fkey"), "notices", type_="foreignkey")
    op.drop_constraint(op.f("notices_receiver_id_fkey"), "notices", type_="foreignkey")
    op.create_foreign_key(None, "notices", "authority_users", ["sender_id"], ["id"])
    op.create_foreign_key(None, "notices", "authority_users", ["receiver_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notices", type_="foreignkey")
    op.drop_constraint(None, "notices", type_="foreignkey")
    op.create_foreign_key(
        op.f("notices_receiver_id_fkey"),
        "notices",
        "authority_holder_persons",
        ["receiver_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("notices_sender_id_fkey"),
        "notices",
        "authority_holder_persons",
        ["sender_id"],
        ["id"],
    )
    # ### end Alembic commands ###
