"""GPS tracking record by vehicle fix

Revision ID: bf62dcd12b1f
Revises: 798647eaf936
Create Date: 2025-11-02 17:20:21.468009

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf62dcd12b1f"
down_revision: Union[str, Sequence[str], None] = "798647eaf936"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    op.add_column("gps_tracking", sa.Column("vehicle_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_gps_tracking_vehicle_no"), table_name="gps_tracking")
    op.drop_index(op.f("idx_vehicle"), table_name="gps_tracking")
    op.create_index("idx_vehicle", "gps_tracking", ["vehicle_id"], unique=False)
    op.drop_index(op.f("idx_vehicle_timestamp"), table_name="gps_tracking")
    op.create_index("idx_vehicle_timestamp", "gps_tracking", ["vehicle_id", "timestamp"], unique=False)
    op.create_index(op.f("ix_gps_tracking_vehicle_id"), "gps_tracking", ["vehicle_id"], unique=False)
    op.create_foreign_key(None, "gps_tracking", "vehicles", ["vehicle_id"], ["id"])
    op.drop_column("gps_tracking", "vehicle_no")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gps_tracking", sa.Column("vehicle_no", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "gps_tracking", type_="foreignkey")
    op.drop_index(op.f("ix_gps_tracking_vehicle_id"), table_name="gps_tracking")
    op.drop_index("idx_vehicle_timestamp", table_name="gps_tracking")
    op.create_index(op.f("idx_vehicle_timestamp"), "gps_tracking", ["vehicle_no", "timestamp"], unique=False)
    op.drop_index("idx_vehicle", table_name="gps_tracking")
    op.create_index(op.f("idx_vehicle"), "gps_tracking", ["vehicle_no"], unique=False)
    op.create_index(op.f("ix_gps_tracking_vehicle_no"), "gps_tracking", ["vehicle_no"], unique=False)
    op.drop_column("gps_tracking", "vehicle_id")
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=False)
    # ### end Alembic commands ###
