"""Change inspection table names

Revision ID: ca70cf2fd644
Revises: 7ee5f81bdbba
Create Date: 2025-10-11 13:26:08.188417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ca70cf2fd644"
down_revision: Union[str, Sequence[str], None] = "7ee5f81bdbba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspection_community_sanitation_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "csc_cleaning_frequency",
            sa.Enum(
                "DAILY",
                "ONCE_IN_THREE_DAYS",
                "WEEKLY",
                "NONE",
                name="csc_clean_freq",
            ),
            nullable=True,
        ),
        sa.Column("electricity_and_water", sa.Boolean(), nullable=True),
        sa.Column("csc_used_by_community", sa.Boolean(), nullable=True),
        sa.Column("pink_toilets_cleaning", sa.Boolean(), nullable=True),
        sa.Column("pink_toilets_used", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_household_waste_collection_and_disposal_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "waste_collection_frequency",
            sa.Enum(
                "DAILY",
                "ONCE_IN_THREE_DAYS",
                "WEEKLY",
                "NONE",
                name="waste_coll_freq",
            ),
            nullable=True,
        ),
        sa.Column("dry_wet_vehicle_segregation", sa.Boolean(), nullable=True),
        sa.Column("covered_collection_in_vehicles", sa.Boolean(), nullable=True),
        sa.Column("waste_disposed_at_rrc", sa.Boolean(), nullable=True),
        sa.Column(
            "rrc_waste_collection_and_disposal_arrangement", sa.Boolean(), nullable=True
        ),
        sa.Column("waste_collection_vehicle_functional", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_other_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firm_paid_regularly", sa.Boolean(), nullable=True),
        sa.Column("cleaning_staff_paid_regularly", sa.Boolean(), nullable=True),
        sa.Column("firm_provided_safety_equipment", sa.Boolean(), nullable=True),
        sa.Column("regular_feedback_register_entry", sa.Boolean(), nullable=True),
        sa.Column("chart_prepared_for_cleaning_work", sa.Boolean(), nullable=True),
        sa.Column("village_visibly_clean", sa.Boolean(), nullable=True),
        sa.Column("rate_chart_displayed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_road_cleaning_inspection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "road_cleaning_frequency",
            sa.Enum("WEEKLY", "FORTNIGHTLY", "MONTHLY", "NONE", name="road_clean_freq"),
            nullable=True,
        ),
        sa.Column(
            "drain_cleaning_frequency",
            sa.Enum(
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "NONE",
                name="drain_clean_freq",
            ),
            nullable=True,
        ),
        sa.Column("disposal_of_sludge_from_drains", sa.Boolean(), nullable=True),
        sa.Column("drain_waste_colllected_on_roadside", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("road_cleaning_inspection_items")
    op.drop_table("community_sanitation_inspection_items")
    op.drop_table("household_waste_collection_and_disposal_inspection_items")
    op.drop_table("other_inspection_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "other_inspection_items",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "firm_paid_regularly", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "cleaning_staff_paid_regularly",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "firm_provided_safety_equipment",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "regular_feedback_register_entry",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "chart_prepared_for_cleaning_work",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "village_visibly_clean", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rate_chart_displayed", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["inspections.id"], name=op.f("other_inspection_items_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("other_inspection_items_pkey")),
    )
    op.create_table(
        "household_waste_collection_and_disposal_inspection_items",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "waste_collection_frequency",
            postgresql.ENUM(
                "DAILY",
                "ONCE_IN_THREE_DAYS",
                "WEEKLY",
                "NONE",
                name="wastecollectionfrequency",
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "dry_wet_vehicle_segregation",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "covered_collection_in_vehicles",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "waste_disposed_at_rrc", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rrc_waste_collection_and_disposal_arrangement",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "waste_collection_vehicle_functional",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
            name=op.f(
                "household_waste_collection_and_disposal_inspection_item_id_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("household_waste_collection_and_disposal_inspection_items_pkey"),
        ),
    )
    op.create_table(
        "community_sanitation_inspection_items",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "csc_cleaning_frequency",
            postgresql.ENUM(
                "DAILY",
                "ONCE_IN_THREE_DAYS",
                "WEEKLY",
                "NONE",
                name="csccleaningfrequency",
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "electricity_and_water", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "csc_used_by_community", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "pink_toilets_cleaning", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "pink_toilets_used", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
            name=op.f("community_sanitation_inspection_items_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("community_sanitation_inspection_items_pkey")
        ),
    )
    op.create_table(
        "road_cleaning_inspection_items",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "road_cleaning_frequency",
            postgresql.ENUM(
                "WEEKLY", "FORTNIGHTLY", "MONTHLY", "NONE", name="roadcleaningfrequency"
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "drain_cleaning_frequency",
            postgresql.ENUM(
                "WEEKLY",
                "FORTNIGHTLY",
                "MONTHLY",
                "NONE",
                name="draincleaningfrequency",
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "disposal_of_sludge_from_drains",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "drain_waste_colllected_on_roadside",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["inspections.id"],
            name=op.f("road_cleaning_inspection_items_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("road_cleaning_inspection_items_pkey")),
    )
    op.drop_table("inspection_road_cleaning_inspection_items")
    op.drop_table("inspection_other_inspection_items")
    op.drop_table("inspection_household_waste_collection_and_disposal_inspection_items")
    op.drop_table("inspection_community_sanitation_inspection_items")
    # ### end Alembic commands ###
