"""add_vdo_contact_number

Revision ID: cd3f6b3b68a9
Revises: 1408ebb1fea3
Create Date: 2026-03-30 00:46:06.855368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3f6b3b68a9'
down_revision: Union[str, Sequence[str], None] = '1408ebb1fea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annual_surveys', sa.Column('vdo_contact_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annual_surveys', 'vdo_contact_number')
    # ### end Alembic commands ###
