"""Notice type and replies

Revision ID: d0469b7a5e2e
Revises: f6d6f76f2995
Create Date: 2025-11-01 13:19:02.705787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0469b7a5e2e"
down_revision: Union[str, Sequence[str], None] = "f6d6f76f2995"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notice_replies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("replier_id", sa.Integer(), nullable=False),
        sa.Column("reply_text", sa.Text(), nullable=False),
        sa.Column("reply_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replier_id"],
            ["authority_holder_persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index("ix_annual_survey_financial_year_fy", "annual_survey_financial_year", ["fy"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_annual_survey_financial_year_fy", table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    op.drop_table("notice_replies")
    # ### end Alembic commands ###
