"""add_account_lockout_fields

Revision ID: d0dfbe7ab554
Revises: 33e322b7889b
Create Date: 2026-02-24 20:58:51.403425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0dfbe7ab554"
down_revision: Union[str, Sequence[str], None] = "33e322b7889b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "authority_users",
        sa.Column(
            "failed_login_attempts", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "authority_users",
        sa.Column("lockout_until", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("authority_users", "lockout_until")
    op.drop_column("authority_users", "failed_login_attempts")
    # ### end Alembic commands ###
