"""Scheme Model

Revision ID: d3843c1318d2
Revises: 78c12eebb01a
Create Date: 2025-09-30 20:12:21.439489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3843c1318d2'
down_revision: Union[str, Sequence[str], None] = '78c12eebb01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('eligibility', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('benefits', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('schemes_pkey'))
    )
    op.create_table('scheme_media',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('scheme_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('media_url', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('scheme_media_scheme_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('scheme_media_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheme_media')
    op.drop_table('schemes')