"""add_date_of_joining_field

Revision ID: db737ed41c1d
Revises: d95767e6e618
Create Date: 2025-09-19 04:57:47.177158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db737ed41c1d'
down_revision: Union[str, Sequence[str], None] = 'd95767e6e618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add date_of_joining column to user_position_holders table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_position_holders', sa.Column('date_of_joining', sa.Date(), nullable=True))
    op.add_column('user_position_holders', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('user_position_holders', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove date_of_joining column from user_position_holders table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_position_holders', 'date_of_joining')
    op.drop_column('user_position_holders', 'start_date')
    op.drop_column('user_position_holders', 'end_date')
    # ### end Alembic commands ###
