"""add_created_at_to_volunteer_registration

Revision ID: e2e40fab6e3c
Revises: b284f4e2b9c3
Create Date: 2026-06-23 20:55:12.554540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e40fab6e3c'
down_revision: Union[str, Sequence[str], None] = 'b284f4e2b9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_registrations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_registrations', 'created_at')
    # ### end Alembic commands ###
