"""Vehicle model for GPS tracking

Revision ID: eb275f7a113e
Revises: d0469b7a5e2e
Create Date: 2025-11-02 15:12:35.369320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb275f7a113e"
down_revision: Union[str, Sequence[str], None] = "d0469b7a5e2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gp_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_no", sa.String(), nullable=False),
        sa.Column("imei", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gp_id"],
            ["gram_panchayats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_gp_vehicle", "vehicles", ["gp_id", "vehicle_no"], unique=True)
    op.create_index(op.f("ix_vehicles_gp_id"), "vehicles", ["gp_id"], unique=False)
    op.create_index(op.f("ix_vehicles_vehicle_no"), "vehicles", ["vehicle_no"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vehicles_vehicle_no"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_gp_id"), table_name="vehicles")
    op.drop_index("idx_gp_vehicle", table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
