"""Public User Model and OTP

Revision ID: f41ac9a94d44
Revises: db737ed41c1d
Create Date: 2025-09-25 17:04:37.919315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f41ac9a94d44'
down_revision: Union[str, Sequence[str], None] = 'db737ed41c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_users",
        sa.Column("id", sa.INTEGER(), autoincrement=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("mobile_number", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="public_users_pkey"),
        sa.UniqueConstraint("email", name="public_users_email_key", postgresql_include=[], postgresql_nulls_not_distinct=False),
        sa.UniqueConstraint("mobile_number", name="public_users_mobile_number_key", postgresql_include=[], postgresql_nulls_not_distinct=False),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "public_user_otps",
        sa.Column("id", sa.INTEGER(), autoincrement=True),
        sa.Column("public_user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("otp", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_verified", sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["public_user_id"], ["public_users.id"], name="public_user_otps_public_user_id_fkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("public_user_otps")
    op.drop_table("public_users")