"""Use Financial Year for Annual Survey

Revision ID: f621e77d41e1
Revises: 290bb1caed5c
Create Date: 2025-10-24 08:45:54.913011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f621e77d41e1"
down_revision: Union[str, Sequence[str], None] = "290bb1caed5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annual_survey_financial_year",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fy", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annual_survey_financial_year_active"), "annual_survey_financial_year", ["active"], unique=False
    )
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    op.add_column("annual_surveys", sa.Column("fy_id", sa.Integer(), nullable=False))
    op.create_index("ix_annual_surveys_fy", "annual_surveys", ["fy_id"], unique=False)
    op.create_index(op.f("ix_annual_surveys_fy_id"), "annual_surveys", ["fy_id"], unique=False)
    op.create_foreign_key(None, "annual_surveys", "annual_survey_financial_year", ["fy_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annual_surveys_fy_id"), table_name="annual_surveys")
    op.drop_index("ix_annual_surveys_fy", table_name="annual_surveys")
    op.drop_column("annual_surveys", "fy_id")
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.drop_index(op.f("ix_annual_survey_financial_year_active"), table_name="annual_survey_financial_year")
    op.drop_table("annual_survey_financial_year")
    # ### end Alembic commands ###
