"""Feedback model one per user

Revision ID: f6d6f76f2995
Revises: 3cb1dee2532a
Create Date: 2025-11-01 12:53:20.169992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6d6f76f2995"
down_revision: Union[str, Sequence[str], None] = "3cb1dee2532a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=True)
    op.create_unique_constraint("unique_auth_user_feedback", "feedback", ["auth_user_id"])
    op.create_unique_constraint("unique_public_user_feedback", "feedback", ["public_user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_public_user_feedback", "feedback", type_="unique")
    op.drop_constraint("unique_auth_user_feedback", "feedback", type_="unique")
    op.drop_index(op.f("ix_annual_survey_financial_year_fy"), table_name="annual_survey_financial_year")
    op.create_index(op.f("ix_annual_survey_financial_year_fy"), "annual_survey_financial_year", ["fy"], unique=False)
    # ### end Alembic commands ###
