"""create vdo_event_images table

Revision ID: fe16f348632b
Revises: 1491c038bf73
Create Date: 2026-07-12 12:18:39.004293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe16f348632b'
down_revision: Union[str, Sequence[str], None] = '1491c038bf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vdo_event_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('vdo_id', sa.Integer(), nullable=False),
    sa.Column('gp_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['gp_id'], ['gram_panchayats.id'], ),
    sa.ForeignKeyConstraint(['vdo_id'], ['authority_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vdo_event_images_block_id'), 'vdo_event_images', ['block_id'], unique=False)
    op.create_index(op.f('ix_vdo_event_images_district_id'), 'vdo_event_images', ['district_id'], unique=False)
    op.create_index(op.f('ix_vdo_event_images_event_id'), 'vdo_event_images', ['event_id'], unique=False)
    op.create_index(op.f('ix_vdo_event_images_gp_id'), 'vdo_event_images', ['gp_id'], unique=False)
    op.create_index(op.f('ix_vdo_event_images_vdo_id'), 'vdo_event_images', ['vdo_id'], unique=False)
    op.drop_index(op.f('ix_annual_survey_financial_year_fy'), table_name='annual_survey_financial_year')
    op.create_index(op.f('ix_annual_survey_financial_year_fy'), 'annual_survey_financial_year', ['fy'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annual_survey_financial_year_fy'), table_name='annual_survey_financial_year')
    op.create_index(op.f('ix_annual_survey_financial_year_fy'), 'annual_survey_financial_year', ['fy'], unique=False)
    op.drop_index(op.f('ix_vdo_event_images_vdo_id'), table_name='vdo_event_images')
    op.drop_index(op.f('ix_vdo_event_images_gp_id'), table_name='vdo_event_images')
    op.drop_index(op.f('ix_vdo_event_images_event_id'), table_name='vdo_event_images')
    op.drop_index(op.f('ix_vdo_event_images_district_id'), table_name='vdo_event_images')
    op.drop_index(op.f('ix_vdo_event_images_block_id'), table_name='vdo_event_images')
    op.drop_table('vdo_event_images')
    # ### end Alembic commands ###
